name = "DemTools"
uuid = "f1514765-0e06-4aee-a94d-d8c2070707bf"
version = "0.1.0"
authors = ["Ivan Utkin <iutkin@ethz.ch>"]

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[workspace]
projects = ["examples"]
