name: Documentation

on:
  push:
    branches:
      - main
    tags:
      - "v*"
    paths:
      - ".github/workflows/documentation.yml"
      - "docs/**"
      - "src/**"
      - "Project.toml"
      - "README.md"
  pull_request:
    paths:
      - ".github/workflows/documentation.yml"
      - "docs/**"
      - "src/**"
      - "Project.toml"
      - "README.md"
  workflow_dispatch:

concurrency:
  group: documentation-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    permissions:
      contents: write
      statuses: write
      deployments: write
      pages: write
      actions: write
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: julia-actions/setup-julia@v3
        with:
          version: "1.12"

      - uses: julia-actions/cache@v3

      - name: Build and deploy documentation
        uses: julia-actions/julia-docdeploy@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
