name: Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: julia-actions/setup-julia@v3
        with:
          version: "1.12"

      - uses: julia-actions/cache@v3

      - name: Run unit tests
        uses: julia-actions/julia-runtest@v1
